### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by elegy0101** [Orangescrum/orangescrum#94]
What can i do with the following messages?, I've given permission and the email support and notify  but it does work
![captura de pantalla de 2015-08-07 18 11 39](https://cloud.githubusercontent.com/assets/3152076/9204377/8c8262ae-4022-11e5-8b9e-a4665371f213.png)

**Comment by ikristher** [comment]
I am also having the same problem, I already set the permission of tmp and webroot folder to 777 but still not working. I was able to login and create projects but I can't upload any files

**Comment by angelo666** [comment]
same problem ...

**Comment by gillesvrstrtn** [comment]
Same problem as well!
Are we missing something important?
It seems that css and js files cannot be loaded.

Your help would be really appreciated, thx.

**Comment by ikristher** [comment]
Also tried the demo site, same problem there as well.

**Comment by Orangescrum** [comment]
Please let us know on what operating system you are installing?

If it is ubuntu, please follow below steps

Step 1:
orangescrum folder path - Make sure please create a folder called 'orangescrum' underneath html folder and copy source 
code here.
/var/www/html/orangescrum
Step 2:
Open this file and edit vi /etc/apache2/apache2.conf
Add this below file ( AllowOverride All instead of AllowOverride None)
<Directory /var/www/html/>
   Options Indexes FollowSymLinks
   AllowOverride All
   Require all granted
</Directory>
Save the file and restart the Apache service.
Step 3:
Enable this module and restart the Apache service
sudo a2enmod rewrite
sudo a2enmod headers
service apache2 restart

**Comment by gillesvrstrtn** [comment]
Ok, it works perfectly now ; thx
